# import library yang dibutuhkan

In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

# Baca data yang dibutuhkan

In [2]:
data = pd.read_csv("data.csv")
data


JENIS KELAMIN  TIPE RUMAH  HARGA RUMAH  JUMLAH TANGGUNGAN      GAJI  \
0                1          36    350000000                  2   3500000   
1                1          45    550000000                  2   4000000   
2                0          45    550000000                  2   5000000   
3                1          54    750000000                  2   4300000   
4                0          45    550000000                  2   6500000   
..             ...         ...          ...                ...       ...   
400              1          45    600000000                  5  10500000   
401              0          54    800000000                  5   8500000   
402              1          54    800000000                  2   4500000   
403              1          36    400000000                  4   8500000   
404              1          36    400000000                  4   5750000   

    JANGKA WAKTU KREDIT  
0                   <20  
1                   <10  
2                   <20  
3                   <20  
4                   <20  
..                  ...  
400                 <10  
401                 <20  
402                 <20  
403                 <10  
404                 <10  

[405 rows x 6 columns]

# Pemberian Label dengan "0" untuk kurun waktu kurang dari 20 tahun dan "1" untuk kurun waktu kurang dari 10 tahun

In [3]:
data['JANGKA WAKTU KREDIT'] = data['JANGKA WAKTU KREDIT'].replace(['<20'],'1')
data['JANGKA WAKTU KREDIT'] = data['JANGKA WAKTU KREDIT'].replace(['<10'],'0')
data

JENIS KELAMIN  TIPE RUMAH  HARGA RUMAH  JUMLAH TANGGUNGAN      GAJI  \
0                1          36    350000000                  2   3500000   
1                1          45    550000000                  2   4000000   
2                0          45    550000000                  2   5000000   
3                1          54    750000000                  2   4300000   
4                0          45    550000000                  2   6500000   
..             ...         ...          ...                ...       ...   
400              1          45    600000000                  5  10500000   
401              0          54    800000000                  5   8500000   
402              1          54    800000000                  2   4500000   
403              1          36    400000000                  4   8500000   
404              1          36    400000000                  4   5750000   

    JANGKA WAKTU KREDIT  
0                     1  
1                     0  
2                     1  
3                     1  
4                     1  
..                  ...  
400                   0  
401                   1  
402                   1  
403                   0  
404                   0  

[405 rows x 6 columns]

# Normalisasi data untuk jenis kelamin, untuk laki-laki bernilai "0" dan untuk perempuan bernilai "1"

In [4]:
encoded = pd.get_dummies(data['JENIS KELAMIN'], prefix='JENIS KELAMIN')
encoded

JENIS KELAMIN_0  JENIS KELAMIN_1
0                  0                1
1                  0                1
2                  1                0
3                  0                1
4                  1                0
..               ...              ...
400                0                1
401                1                0
402                0                1
403                0                1
404                0                1

[405 rows x 2 columns]

In [5]:
data = data.drop(['JENIS KELAMIN'], axis = 1)
data

TIPE RUMAH  HARGA RUMAH  JUMLAH TANGGUNGAN      GAJI JANGKA WAKTU KREDIT
0            36    350000000                  2   3500000                   1
1            45    550000000                  2   4000000                   0
2            45    550000000                  2   5000000                   1
3            54    750000000                  2   4300000                   1
4            45    550000000                  2   6500000                   1
..          ...          ...                ...       ...                 ...
400          45    600000000                  5  10500000                   0
401          54    800000000                  5   8500000                   1
402          54    800000000                  2   4500000                   1
403          36    400000000                  4   8500000                   0
404          36    400000000                  4   5750000                   0

[405 rows x 5 columns]

In [6]:
data['JENIS KELAMIN_0'], data['JENIS KELAMIN_1'] = encoded['JENIS KELAMIN_0'], encoded['JENIS KELAMIN_1']
data


TIPE RUMAH  HARGA RUMAH  JUMLAH TANGGUNGAN      GAJI JANGKA WAKTU KREDIT  \
0            36    350000000                  2   3500000                   1   
1            45    550000000                  2   4000000                   0   
2            45    550000000                  2   5000000                   1   
3            54    750000000                  2   4300000                   1   
4            45    550000000                  2   6500000                   1   
..          ...          ...                ...       ...                 ...   
400          45    600000000                  5  10500000                   0   
401          54    800000000                  5   8500000                   1   
402          54    800000000                  2   4500000                   1   
403          36    400000000                  4   8500000                   0   
404          36    400000000                  4   5750000                   0   

     JENIS KELAMIN_0  JENIS KELAMIN_1  
0                  0                1  
1                  0                1  
2                  1                0  
3                  0                1  
4                  1                0  
..               ...              ...  
400                0                1  
401                1                0  
402                0                1  
403                0                1  
404                0                1  

[405 rows x 7 columns]

# Normalisasi data untuk Tipe Rumah

In [7]:
encoded = pd.get_dummies(data['TIPE RUMAH'], prefix='TIPE RUMAH')
encoded

TIPE RUMAH_36  TIPE RUMAH_45  TIPE RUMAH_54
0                1              0              0
1                0              1              0
2                0              1              0
3                0              0              1
4                0              1              0
..             ...            ...            ...
400              0              1              0
401              0              0              1
402              0              0              1
403              1              0              0
404              1              0              0

[405 rows x 3 columns]

In [8]:
data = data.drop(['TIPE RUMAH'], axis = 1)
data['TIPE RUMAH_36'], data['TIPE RUMAH_45'], data['TIPE RUMAH_54'] = encoded['TIPE RUMAH_36'], encoded['TIPE RUMAH_45'], encoded['TIPE RUMAH_54']
data

HARGA RUMAH  JUMLAH TANGGUNGAN      GAJI JANGKA WAKTU KREDIT  \
0      350000000                  2   3500000                   1   
1      550000000                  2   4000000                   0   
2      550000000                  2   5000000                   1   
3      750000000                  2   4300000                   1   
4      550000000                  2   6500000                   1   
..           ...                ...       ...                 ...   
400    600000000                  5  10500000                   0   
401    800000000                  5   8500000                   1   
402    800000000                  2   4500000                   1   
403    400000000                  4   8500000                   0   
404    400000000                  4   5750000                   0   

     JENIS KELAMIN_0  JENIS KELAMIN_1  TIPE RUMAH_36  TIPE RUMAH_45  \
0                  0                1              1              0   
1                  0                1              0              1   
2                  1                0              0              1   
3                  0                1              0              0   
4                  1                0              0              1   
..               ...              ...            ...            ...   
400                0                1              0              1   
401                1                0              0              0   
402                0                1              0              0   
403                0                1              1              0   
404                0                1              1              0   

     TIPE RUMAH_54  
0                0  
1                0  
2                0  
3                1  
4                0  
..             ...  
400              0  
401              1  
402              1  
403              0  
404              0  

[405 rows x 9 columns]

# Normalisasi data untuk Harga Rumah, Jumlah tanggungan, dan Gaji

In [9]:
array = data.values

X = array[:, 0:3]
print(X)


[[350000000 2 3500000]
 [550000000 2 4000000]
 [550000000 2 5000000]
 ...
 [800000000 2 4500000]
 [400000000 4 8500000]
 [400000000 4 5750000]]


In [10]:
min_max_scaler = preprocessing.MinMaxScaler(
    feature_range=(0, 1))  # inisialisasi normalisasi MinMax
file = min_max_scaler.fit_transform(X)  # transformasi MinMax untuk fitur
dataset = pd.DataFrame(
    {'HARGA RUMAH': file[:, 0], 'JUMLAH TANGGUNGAN': file[:, 1], 'GAJI': file[:, 2]})


pd.DataFrame(dataset)

HARGA RUMAH  JUMLAH TANGGUNGAN      GAJI
0       0.000000           0.000000  0.000000
1       0.444444           0.000000  0.043478
2       0.444444           0.000000  0.130435
3       0.888889           0.000000  0.069565
4       0.444444           0.000000  0.260870
..           ...                ...       ...
400     0.555556           1.000000  0.608696
401     1.000000           1.000000  0.434783
402     1.000000           0.000000  0.086957
403     0.111111           0.666667  0.434783
404     0.111111           0.666667  0.195652

[405 rows x 3 columns]

In [11]:
drop = data.drop(['HARGA RUMAH','JUMLAH TANGGUNGAN', 'GAJI'], axis=1)

In [12]:
data = pd.merge(dataset, drop, left_index=True, right_index=True)
data

HARGA RUMAH  JUMLAH TANGGUNGAN      GAJI JANGKA WAKTU KREDIT  \
0       0.000000           0.000000  0.000000                   1   
1       0.444444           0.000000  0.043478                   0   
2       0.444444           0.000000  0.130435                   1   
3       0.888889           0.000000  0.069565                   1   
4       0.444444           0.000000  0.260870                   1   
..           ...                ...       ...                 ...   
400     0.555556           1.000000  0.608696                   0   
401     1.000000           1.000000  0.434783                   1   
402     1.000000           0.000000  0.086957                   1   
403     0.111111           0.666667  0.434783                   0   
404     0.111111           0.666667  0.195652                   0   

     JENIS KELAMIN_0  JENIS KELAMIN_1  TIPE RUMAH_36  TIPE RUMAH_45  \
0                  0                1              1              0   
1                  0                1              0              1   
2                  1                0              0              1   
3                  0                1              0              0   
4                  1                0              0              1   
..               ...              ...            ...            ...   
400                0                1              0              1   
401                1                0              0              0   
402                0                1              0              0   
403                0                1              1              0   
404                0                1              1              0   

     TIPE RUMAH_54  
0                0  
1                0  
2                0  
3                1  
4                0  
..             ...  
400              0  
401              1  
402              1  
403              0  
404              0  

[405 rows x 9 columns]

# Drop jangka waktu kredit

In [13]:
y = data['JANGKA WAKTU KREDIT']
x = data.drop(['JANGKA WAKTU KREDIT'], axis=1)

In [14]:
print(x)
print(y)

     HARGA RUMAH  JUMLAH TANGGUNGAN      GAJI  JENIS KELAMIN_0  \
0       0.000000           0.000000  0.000000                0   
1       0.444444           0.000000  0.043478                0   
2       0.444444           0.000000  0.130435                1   
3       0.888889           0.000000  0.069565                0   
4       0.444444           0.000000  0.260870                1   
..           ...                ...       ...              ...   
400     0.555556           1.000000  0.608696                0   
401     1.000000           1.000000  0.434783                1   
402     1.000000           0.000000  0.086957                0   
403     0.111111           0.666667  0.434783                0   
404     0.111111           0.666667  0.195652                0   

     JENIS KELAMIN_1  TIPE RUMAH_36  TIPE RUMAH_45  TIPE RUMAH_54  
0                  1              1              0              0  
1                  1              0              1              0  
2  

# Split Data training dan testing 70 : 30 

In [15]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=42)

# Pembuatan Model untuk melakukan testing

In [16]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(x_train, y_train);

# Prediksi dari model yang dibuat

In [17]:
pred = model.predict(x_test)
print(pred)

['1' '1' '0' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '0' '0' '1'
 '0' '1' '1' '1' '1' '0' '1' '1' '1' '1' '1' '0' '1' '1' '0' '1' '0' '1'
 '1' '1' '1' '0' '1' '1' '1' '0' '1' '1' '1' '1' '0' '1' '1' '1' '1' '0'
 '1' '1' '0' '1' '1' '1' '0' '1' '0' '0' '1' '1' '1' '1' '1' '0' '0' '0'
 '1' '1' '1' '0' '0' '1' '1' '0' '1' '1' '1' '1' '1' '1' '0' '0' '1' '1'
 '1' '1' '1' '1' '0' '1' '1' '1' '1' '0' '0' '1' '1' '1' '1' '1' '0' '1'
 '1' '1' '1' '0' '0' '1' '0' '1' '0' '1' '1' '1' '0' '1']


In [18]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

mat = confusion_matrix(y_test, pred)
mat

array([[32,  4],
       [ 1, 85]], dtype=int64)

# Hasil akhir dari prediksi penentuan kelayakan kredit rumah dengan akurasi sebesar 96%

In [19]:
report = classification_report(y_test,pred)
print(report)

              precision    recall  f1-score   support

           0       0.97      0.89      0.93        36
           1       0.96      0.99      0.97        86

    accuracy                           0.96       122
   macro avg       0.96      0.94      0.95       122
weighted avg       0.96      0.96      0.96       122

